"""empty message

Revision ID: 283ebe1b54bc
Revises: 1dbdbaef0448
Create Date: 2019-10-06 16:52:57.547184

"""

# revision identifiers, used by Alembic.
revision = '283ebe1b54bc'
down_revision = '1dbdbaef0448'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
